<?php
/** @var \BrunoDuarte\MultipleWishlist\Block\Product\View $block */
?>

<?php if ($block->canDisplayBlock()): ?>
    <style>
        .box-multiple-wishlist {
            display: block;
            margin: 1.5rem 0;
        }
        .box-multiple-wishlist .fieldset {
            position: relative;
            display: -webkit-flex;
            display: -ms-flexbox;
            display: -ms-flex;
            display: flex;
            -webkit-align-items: center;
            -ms-align-items: center;
            align-items: center;
        }
        .box-multiple-wishlist .field {
            display: block;
            padding: 1px;
            box-shadow: inset 0 0 0 1px #cccccc;
            border-radius: 4px;
            background-color: #ffffff;
            max-width: 25rem;
            height: 5rem;
            margin: 0 16px 0 0 !important;
        }
        .box-multiple-wishlist .input-field {
            width: 100%;
            height: 4rem;
            border-radius: 4px;
            border: none;
            margin: 0;
            padding: 0;
            color: #000000;
        }
        .box-multiple-wishlist .toMultipleWishlist {
            max-width: 160px;
            padding: 1rem;
        }
    </style>

    <div class="box-multiple-wishlist">
        <div class="fieldset">
            <div class="field">
                <select class="input-field" id="" name="">
                    <option value=""></option>
                    <option value="2">Eletrônicos</option>
                    <option value="1">Ferramentas</option>
                </select>
            </div>
            <button type="button" title="Adicionar à lista de desejo" class="action primary toMultipleWishlist" id="multiple-wishlist-addproduct-button">
                <span>Adicionar à Lista de Desejo</span>
            </button>
        </div>
    </div>

    <script>
        $(document).ready(function() {
            $('#multiple-wishlist-addproduct-button').on('click', function() {
                alert('Implementar a ação de Adicionar o Produto à Lista de Desejo.');
            });
        });
    </script>
<?php endif; ?>
